version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - proxysql
    environment:
      DATABASE_URL: mysql://user:password@proxysql:6032/database
    restart: always

  db1:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db1-data:/var/lib/mysql
    restart: always

  db2:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db2-data:/var/lib/mysql
    restart: always

  db3:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db3-data:/var/lib/mysql
    restart: always

  proxysql:
    build: ./proxySql
    ports:
      - "6032:6032"
    depends_on:
      - db1
      - db2
      - db3
    environment:
      PROXYSQL_USERNAME: user
      PROXYSQL_PASSWORD: password
      PROXYSQL_HOST: db1
      PROXYSQL_PORT: 3306
      PROXYSQL_HOST2: db2
      PROXYSQL_PORT2: 3306
      PROXYSQL_HOST3: db3
      PROXYSQL_PORT3: 3306
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always

volumes:
  db1-data:
  db2-data:
  db3-data:
