FROM proxysql/proxysql:latest

ENV PROXYSQL_USERNAME=user
ENV PROXYSQL_PASSWORD=password

# Install additional tools for development (e.g., vim, curl)
RUN apt-get update && apt-get install -y vim curl

COPY ./proxySql.cnf /etc/proxysql/proxysql.cnf

CMD ["proxysql", "-f", "/etc/proxysql/proxysql.cnf"]
